name: Django CI/CD Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 146.190.85.59
          username: root
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/azz_ci_cd/backend
            git pull
            systemctl restart azz.service
            systemctl reload nginx.service